### ISSUE TITLE
Needs proper packaging

### ISSUE THREAD

**Issue by walkerh** [hgsc-project-managers/ngsi-pm#10]
The scripts in the bin directory should be proper entry points in a setup.py.

**Comment by itsmarcy** [comment]
Would it be okay if I try to do this @walkerh @jekwatt ? I'm unable to assign myself and wasn't sure if @jekwatt was planning to do this.

**Comment by jekwatt** [comment]
@itsmarcy Would be wonderful if you can do this.

**Comment by walkerh** [comment]
Go for it @itsmarcy !

**Comment by itsmarcy** [comment]
PR #24 has been created to address the issue and has now been merged.
Closing the issue as this is now done.
