### ISSUE TITLE
Having an updated environment causes pytest to fail

### ISSUE THREAD

**Issue by itsmarcy** [hgsc-project-managers/ngsi-pm#16]
Updating an environment causes test to fail

Attached is the environment where test pass without issue. Once you update the conda environment, the test fail.

[environment.txt](https://github.com/BCM-HGSC/ngsi-pm/files/3258080/environment.txt)

**Comment by jekwatt** [comment]
Proper packing would help.  I do not have the same issue, so we will need to figure this out together.

**Comment by itsmarcy** [comment]
After investigating, everything in the environment can be safely updated **except** for pytest. Pytest 3.3.0 introduced capturing from the `logging` module.
I will be updating the test to use `caplog`  as suggested in their documentation if the application uses the `loggin` module. This will let the test be able to safely run in the newest pytest version.

**Comment by itsmarcy** [comment]
PR #28 fixes this issue and it is now merged to `master`. Closing.
