### ISSUE TITLE
ngsi_pm_sh does not isolate execution

### ISSUE THREAD

**Issue by walkerh** [hgsc-project-managers/ngsi-pm#26]
The version of the Python entry points that are invoked in `*rg_check.sh` is determined by PATH instead of environment. Can resolve this by adding a build script that forces PATH and adjusts the shebang. See: [this example](https://github.com/BCM-HGSC/packaging_workshop/blob/0767575e0b8d2bff86e0631cee6492133f55f056/step_c/pipeline_1/conda.recipe/build.sh).

**Comment by itsmarcy** [comment]
PR #29 has been merged, resolving this issue. Closing.
