### ISSUE TITLE
Need branches and tags for mplx_qc 1.0 and 1.1

### ISSUE THREAD

**Issue by walkerh** [hgsc-project-managers/ngsi-pm#4]
I propose that you create the following branches:

* `mplx_qc-1.0`
* `mplx_qc-1.1`

I also propose creating this release (tag):

* `mplx_qc-1.0.0-rc3`
* Notes:
    * Remapped error codes to start at 2.
    * Added tests for remaining error codes.

For examples of what I'm talking about:

* https://github.com/Submissions/ngsi-pm/branches/all
* https://github.com/Submissions/ngsi-pm/releases

**Comment by walkerh** [comment]
You have created the branches. The next step would be to create a release from `mplx_qc-1.0`, assuming that that branch is still set to https://github.com/hgsc-project-managers/ngsi-pm/commit/38e6feaa115393b72826144914f472e2da2f7fe2, the release would be named `mplx_qc-1.0.0-rc3`.

**Comment by jekwatt** [comment]
Done.
